PREFIX=../mk
-include $(PREFIX)/setup.mk

TARGET	= liburlparser.so

SOURCE	= \
	url_parser.cpp

## End sources definition
INCLUDE += -I./

LDFLAGS		= 
LIBS		= 

PUBLIC_HEADERS = \
	url_parser.hpp

-include $(PREFIX)/lib.mk
